# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    AppBundle\Repository\AdminRepository:
        autowire: true
        tags: ['doctrine.repository_service']
    AppBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    AppBundle\EventListeners\ExceptionListener:
        arguments:
            - '@AppBundle\Services\LogService'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.user:
        class: AppBundle\Services\UserService
        public: true

    app.log:
        class: AppBundle\Services\LogService
        public: true

    app.testItem:
        class: AppBundle\Services\TestItemService
        public: true
        arguments:
            - '@AppBundle\Factory\TestItemFactory'
            - '@AppBundle\Factory\TestItemQuestionsFactory'
            - '@AppBundle\Factory\TestItemAnswersFactory'
            - '@AppBundle\Factory\TestItemResultsFactory'
            - '@AppBundle\Manager\TestItemManager'
            - '@AppBundle\Manager\TestItemQuestionsManager'
            - '@AppBundle\Manager\TestItemAnswersManager'
            - '@AppBundle\Manager\TestItemResultsManager'
            - '@AppBundle\Services\LogService'
            - '@doctrine.orm.entity_manager'

    app.htmlTestParser:
        class: AppBundle\Services\HtmlTestParser
        public: true

    app.categoryParser:
        class: AppBundle\Services\CategoryParser
        public: true
        arguments:
            - '@AppBundle\Services\HtmlTestParser'
            - '@doctrine.orm.entity_manager'

    app.userStatistic:
        class: AppBundle\Services\UserStatisticService
        public: true
        arguments:
            - '@AppBundle\Services\LogService'
            - '@doctrine.orm.entity_manager'
            - '@AppBundle\Factory\UserStatistic\RecentTestsFactory'
            - '@AppBundle\Factory\UserStatistic\SavedTestsFactory'
            - '@AppBundle\Manager\UserStatistic\RecentTestsManager'
            - '@AppBundle\Manager\UserStatistic\SavedTestsManager'
            - '@AppBundle\Factory\UserStatistic\PassedFactory'
            - '@AppBundle\Manager\UserStatistic\PassedManager'
