
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Repository\AdminRepository:
        autowire: true
        tags: ['doctrine.repository_service']
    AppBundle\Repository\UserRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    AppBundle\EventListeners\ExceptionListener:
        arguments:
            - '@AppBundle\Services\LogService'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.user:
        class: AppBundle\Services\UserService
        public: true

    app.log:
        class: AppBundle\Services\LogService
        public: true

    app.testItem:
        class: AppBundle\Services\TestItemService
        public: true
        arguments:
            - '@AppBundle\Factory\TestItemFactory'
            - '@AppBundle\Factory\TestItemQuestionsFactory'
            - '@AppBundle\Factory\TestItemAnswersFactory'
            - '@AppBundle\Factory\TestItemResultsFactory'
            - '@AppBundle\Manager\TestItemManager'
            - '@AppBundle\Manager\TestItemQuestionsManager'
            - '@AppBundle\Manager\TestItemAnswersManager'
            - '@AppBundle\Manager\TestItemResultsManager'
            - '@AppBundle\Services\LogService'
            - '@doctrine.orm.entity_manager'

    app.htmlTestParser:
        class: AppBundle\Services\HtmlTestParser
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    app.categoryParser:
        class: AppBundle\Services\CategoryParser
        public: true
        arguments:
            - '@AppBundle\Services\HtmlTestParser'
            - '@doctrine.orm.entity_manager'

    app.userStatistic:
        class: AppBundle\Services\UserStatisticService
        public: true
        arguments:
            - '@AppBundle\Services\LogService'
            - '@doctrine.orm.entity_manager'
            - '@AppBundle\Factory\UserStatistic\RecentTestsFactory'
            - '@AppBundle\Factory\UserStatistic\SavedTestsFactory'
            - '@AppBundle\Manager\UserStatistic\RecentTestsManager'
            - '@AppBundle\Manager\UserStatistic\SavedTestsManager'
            - '@AppBundle\Factory\UserStatistic\PassedFactory'
            - '@AppBundle\Manager\UserStatistic\PassedManager'

    app.db:
        class: AppBundle\Services\DbService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'